quarkus:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: crosswords
  swagger-ui:
    always-include: true
    path: /documentation

mp:
  openapi:
    scan:
      disable: true
