FROM fabric8/java-alpine-openjdk14-jre
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV AB_ENABLED=jmx_exporter
COPY build/*-runner.jar /deployments/app.jar
ENTRYPOINT ["/deployments/run-java.sh"]
